version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_DB: fluent_interaction
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server # O Dockerfile do servidor deve estar na pasta './server'
    container_name: server_container
    depends_on:
      - postgres
    ports:
      - "8080:3000"
    environment:
      DATABASE_URL: postgres://postgres:docker@postgres/fluent_interaction

  client:
    build:
      context: ./client # O Dockerfile do cliente deve estar na pasta './client'
    container_name: client_container
    ports:
      - "3000:80"

volumes:
  postgres_data:
